trufla-technology/android-tru-forms

android-tru-forms/src/main/java/com/trufla/androidtruforms/SchemaModels/ArrayInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/SchemaModels/ObjectInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/SchemaModels/ObjectProperties.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/SchemaViews/TruSectionView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/SerializationAdapters/ObjectPropertiesAdapter.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/SerializationAdapters/SchemaInstanceAdapter.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/TruUtils.java
android-tru-forms/src/test/java/com/trufla/androidtruforms/ExampleUnitTest.java
android-tru-forms/src/test/java/com/trufla/androidtruforms/TestProperJsonConversion.java

build up type adapters to convert json strings to proper POJO's
Type Adapters provided :: ObjectPropertiesAdapter

feat:: make type adapters to parse object properties 

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/models/ObjectInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/ObjectProperties.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/SchemaDocument.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/SchemaInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/SchemaBaseView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruArrayView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruBooleanView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruFormView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruNumericView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruObjectView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruSectionView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruStringView.java
android-tru-forms/src/main/res/layout/tru_array_view.xml
android-tru-forms/src/main/res/layout/tru_form_view.xml
app/src/main/java/com/trufla/androidtruformssample/MainActivity.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/raw/claims_edited.json
build.gradle

- add composite views 
TruObjectView represent the composite views have to concrete implementations TruSectionView ,TruFromView which handle both ObjectInstance and SchemaDocumentInstance

Composite views

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/SchemaBuilder.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/SchemaViews.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/TruFormActivity.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/adapters/deserializers/ObjectPropertiesDeserializer.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/adapters/deserializers/ObjectPropertiesDeserializerWithConstValues.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/adapters/deserializers/SchemaInstanceDeserializer.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/ArrayInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/BooleanInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/DataInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/EnumInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/NumericInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/ObjectInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/SchemaDocument.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/SchemaInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/StringInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruArrayView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruEnumDataView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruEnumView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruSectionView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/utils/ValueToSchemaMapper.java
app/src/main/java/com/trufla/androidtruformssample/TestFormActivity.java
app/src/main/res/layout/test_form_activity.xml

Map Json to existing schema by adding the json values as const in the Schmea

Schema value mapper

---

.idea/misc.xml
.idea/modules.xml
android-tru-forms/src/main/java/com/trufla/androidtruforms/TruFormFragment.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java
android-tru-forms/src/main/res/values/strings.xml

fix null in selectors like edit properties

---

.idea/gradle.xml
.idea/misc.xml
.idea/modules.xml
android-tru-forms/build.gradle
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruStringView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/utils/TruUtils.java
android-tru-forms/src/main/res/values/strings.xml
app/src/main/res/raw/claims.json
app/src/main/res/raw/claims_edited.json

feat: handle required filed in case one of , solve spelling mistakes , change error message in change email

Issue 310 371

---

.idea/misc.xml
android-tru-forms/build.gradle
android-tru-forms/src/main/java/com/trufla/androidtruforms/models/StringInstance.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruDatePickerView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruStringView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/utils/BitmapUtils.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/utils/TruUtils.java
app/src/main/java/com/trufla/androidtruformssample/TestFormActivity.java
app/src/main/res/raw/claims.json
app/src/main/res/raw/claims_edited.json

to solve issues number (#386 , #391 , #386)

Prevent user from selecting date in past, reduce image bitmap size

---

.idea/misc.xml
android-tru-forms/build.gradle

rebuild gradle

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/SchemaBaseView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruStringView.java
android-tru-forms/src/main/res/layout/tru_string_view.xml

Fix :T ext Fields that contains large texts should be wrapped so that all the data entered appear

edit text wrap in lines if the text is long

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/utils/BitmapUtils.java

Add regex to the decoding method.

fix base64 decoding issue using Regular Expression.

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruEnumView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/utils/BitmapUtils.java

Fix  issues 
1. 2253 
2. 2242
3. 2241

fix upload image issue and drop down issue

---

android-tru-forms/build.gradle
android-tru-forms/src/main/java/com/trufla/androidtruforms/PDFViewerActivity.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/utils/PDFUtil.java
android-tru-forms/src/main/res/layout/pdfviewer.xml

Trum 4067 android allow pdf file type upload viewing 

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java

remove pdfium library

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java

fix pdfium DefNotFoundException

fix pdfium DefNotFoundException

---

android-tru-forms/build.gradle
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/utils/PDFUtil.java

remove pdfium

---

android-tru-forms/build.gradle
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/utils/PDFUtil.java

Add Pdfium Library

---

android-tru-forms/src/main/res/layout/photo_viewer.xml

fix photo viewer layout

---

android-tru-forms/build.gradle
android-tru-forms/src/main/java/com/trufla/androidtruforms/PDFViewerActivity.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/PhotoViewerActivity.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/utils/PDFUtil.java
android-tru-forms/src/main/res/layout/pdfviewer.xml
android-tru-forms/src/main/res/layout/photo_viewer.xml

fix issues

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/FileCompressTask.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruStringView.java
android-tru-forms/src/main/res/layout/tru_number_view.xml

add validations to driver_license_number & number of drivers

Sign up process update

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruStringView.java
android-tru-forms/src/main/res/layout/tru_number_view.xml

add validations to postal code

Question validations

---

.idea/modules.xml
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruDatePickerView.java

Enhance the date Picker component

Enhance the date Picker component

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruDatePickerView.java

ENhance date picker

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/PhotoViewerActivity.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java

fix image preview in claims & change request

fix attached images

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruDatePickerView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruEnumDataView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruEnumView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruStringView.java
android-tru-forms/src/main/java/com/trufla/androidtruforms/utils/TruUtils.java

remove capitalize from titles and  add astric to required field

remove capitalize from titles and  add astric to required field

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruTextAreaView.java

remove capitalize from titles and  add astric to required field 2

remove capitalize from titles and  add astric to required field 2

---

android-tru-forms/src/main/java/com/trufla/androidtruforms/truviews/TruPhotoPickerView.java
android-tru-forms/src/main/res/values-fr/strings.xml
android-tru-forms/src/main/res/values/strings.xml

5751_OTIP_French_Translation_Suggestions_-_Update_3_JSON_Schema_Upload_Control
